robot --outputdir result\TestLab E:\PythonProject\APIAutomation\testlab.robot
robot --outputdir result\Del E:\PythonProject\APIAutomation\DelAPI.robot
robot --outputdir result\Delete E:\PythonProject\APIAutomation\Delete.robot
robot --outputdir result\GetAPI E:\PythonProject\APIAutomation\GetAPI.robot
robot --outputdir result\GetDR E:\PythonProject\APIAutomation\GetDR.robot
robot --outputdir result\GetList E:\PythonProject\APIAutomation\GetList.robot
robot --outputdir result\GetLR E:\PythonProject\APIAutomation\GetLR.robot
robot --outputdir result\GetRUserNotFound E:\PythonProject\APIAutomation\GetRUserNotFound.robot
robot --outputdir result\GetSR E:\PythonProject\APIAutomation\GetSR.robot
robot --outputdir result\OptimizLab E:\PythonProject\APIAutomation\OptimizLab.robot
